### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by cenchaojun** [PJLallen/CalibNet#1]
Thank you very much for your excellent work on the SOD.
I was wondering if you plan to release your code and dataset anytime soon.

**Comment by PJLallen** [comment]
Sorry, the manu is still under review. 
We will release the dataset as soon as the review results are available.

**Comment by PJLallen** [comment]
> Thank you very much for your excellent work on the SOD. I was wondering if you plan to release your code and dataset anytime soon.

Our dataset and source code are publicly available now, thanks for your attention.

**Comment by PJLallen** [comment]
> Thank you very much for your excellent work on the SOD. I was wondering if you plan to release your code and dataset anytime soon.

Our dataset and source code are publicly available now, thanks for your attention.
