### ISSUE TITLE
Communicate, looking forward to getting a reply

### ISSUE THREAD

**Issue by surelon** [PJLallen/CalibNet#2]
Dear author, hello! I read your paper CalibNet: Dual-branch Cross-modal Calibration for RGB-D
Salient Instance Segmentation has gained a lot. When can I obtain the open source code? Want to repeat and learn, thank you!

**Comment by PJLallen** [comment]
Hi, this paper has been accepted at TIP 2024 yesterday. We will open the source code and dataset in a week! Thanks for your attention.

**Comment by surelon** [comment]
Congratulations! Thank you for your contributions and selfless dedication to the field of instance segmentation
